# تعطيل إحصائيات CocoaPods لتقليل مشاكل الاتصال
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '14.0'

# التأكد من أن Flutter مدمج مع Pods
require File.expand_path(File.join('..', 'flutter', 'tools', 'podhelper'), __FILE__)

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
